version: '3.8'

services:

  # PostgreSQL database
  postgres:
    image: postgres:16
    container_name: dhamma-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dhamma_db
      - POSTGRES_USER=dhamma_user
      - POSTGRES_PASSWORD=dhamma_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dhamma-network

volumes:
  postgres_data:

networks:
  dhamma-network:
    driver: bridge
